### ISSUE TITLE
X dependencies on RHEL

### ISSUE THREAD

**Issue by edburns** [galiacheng/oracle-forms-reports-weblogic-on-azure#1]
Hello @galiacheng , we observed that on RHEL an additional command was necessary.

```bash
yum install libXtst
```

**Comment by galiacheng** [comment]
Yes, I found those dependencies are also needed on RHEL:

```
sudu yum install -y libSM
sudo yum install -y libXrender
```

**Comment by galiacheng** [comment]
Fixed in https://github.com/galiacheng/oracle-forms-reports-weblogic-on-azure/commit/e3c6f283f310255f57190344b7aee0f03966b991
