### ISSUE TITLE
Issue with Create and start Reports tools via python

### ISSUE THREAD

**Issue by PrikshitSh** [galiacheng/oracle-forms-reports-weblogic-on-azure#3]
**ISSUE** 

Unable to Create and start Reports components with failed to activate the changes.

**SYMPTOMS**

Trying to create and start Reports Tool via python:

```
# the virtual IP address created in [Configure Virtual IP for Admin Server](#configure-virtual-ip-for-admin-server)
adminServerIP=10.0.0.16
# Username of WebLogic admin account
wlsUsername="weblogic"
# Password of WebLogic admin account
wlsPassword="Secret123456"
# Keep the index value the same with Azure Virtual Machine index
index=3

repToolsName="reptools${index}"
repToolsTargetMachine="mspVM${index}"
cat <<EOF >create-reportstools.py
connect("${wlsUsername}","${wlsPassword}", "${adminServerIP}:7001")
createReportsToolsInstance(instanceName="${repToolsName}", machine="${repToolsTargetMachine}")
EOF
```

**Running the script is executed using WLST online mode:**

`/u01/app/wls/install/oracle/middleware/oracle_home/oracle_common/common/bin/wlst.sh create-reportstools.py`

**Issue after running the script executed using WLST online mode**

This Exception error occurred.
```
java.lang.RuntimeException: Timed out waiting for completion:  Activate State: STATE_DISTRIBUTING Target Servers States: WLS_FORMS1 STATE_FAILED admin STATE_FAILED WLS_REPORTS1 STATE_FAILED reptools5 STATE_FAILED WLS_REPORTS4 STATE_FAILED WLS_FORMS4 STATE_FAILED WLS_FORMS5 STATE_FAILED WLS_REPORTS5 STATE_FAILED WLS_FORMS2 STATE_FAILED WLS_REPORTS2 STATE_FAILED WLS_REPORTS3 STATE_FAILED WLS_FORMS3 STATE_FAILED 
Problem invoking WLST - Traceback (innermost last):
```

**Comment by PrikshitSh** [comment]
**CAUSE**

The above issue is because of the Admin Server not the able to activate the changes due to time not sync/not same between all the servers. 

**SOLUTION**

Check the date and Time for admin and all managed machines.  (Make sure date and time between admin server and all managed msp machines is same.)

**Comment by galiacheng** [comment]
Thanks for the issue and solution @PrikshitSh
